M48
; DRILL file {KiCad (6.0.10)} date Thu Feb 16 14:19:03 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-16T14:19:03-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0598
%
G90
G05
T1
X5.5Y-3.8
X5.7Y-3.9
X5.8Y-4.3
X6.188Y-4.112
T2
X5.8Y-3.6
X6.0Y-3.6
T0
M30
